title: Niels Talens
logo: /assets/images/site-images/logo.svg
url: "https://www.nielstalens.nl"
baseurl: ""

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  # email: "site@some.nl"
  github: "https://github.com/NielsTalens"
  # telegram: "https://t.me/"
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"
  # threads: "https://www.threads.net/@example"
  linkedin: "https://www.linkedin.com/in/nielstalens/"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
